FROM node:10 AS builder

WORKDIR /app


COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:latest

COPY --from=builder /app/dist /app/dist
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
