export const CREATE_GROUP = 'CREATE_GROUP';
export const GET_GROUPS = 'GET_GROUPS';
export const GET_GROUPS_BY_CLIENT = 'GET_GROUPS_BY_CLIENT';

export const GET_CURRENT_GROUP = 'GET_CURRENT_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const EDIT_GROUP = 'EDIT_GROUP';

export const CREATE_PARTICIPANT = 'CREATE_PARTICIPANT';
export const DELETE_PARTICIPANT = 'DELETE_PARTICIPANT';

export const GET_PARTICIPANTS_REQUEST = 'GET_PARTICIPANTS_REQUEST';
export const APPROVE_PARTICIPANTS_REQUEST = 'APPROVE_PARTICIPANTS_REQUEST';

export const CREATE_INVITE = 'CREATE_INVITE';
export const GET_INVITE = 'GET_INVITE';
export const APPROVE_INVITE = 'APPROVE_INVITE';
export const CANCEL_INVITE = 'CANCEL_INVITE';

// сместить владельца групп
export const REPLACE_GROUPS_OWNER = 'REPLACE_GROUPS_OWNER'



