version: "3.7"
services:
  connbackend:
    build:
      context: .
      dockerfile: Dockerfile_nodejs
      args:
        - DB_URL
    image: connbackend/temp
    container_name: connbackend
    restart: always
    depends_on:
      - mongodb
    command: bash -c "node deploy_scripts/nodejs_init/wait_for_mongo.js && npm start"
    volumes:
      - ./:/app
      - /app/node_modules
      - ./static:/app/static
      - ./deploy_scripts/nodejs_init:/app/nodejs_init
    ports:
        - "4000:4000"
    env_file: .env.dev
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    restart: always
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /var/log
    env_file: .env.dev
    volumes:
      - ./data/db:/data/db
      - ./deploy_scripts/mongo_init:/docker-entrypoint-initdb.d
    ports:
        - 27017:27017
  # connfrontend:
  #   build:
  #     context: ./vue-client
  #     dockerfile: Dockerfile_vue
  #   image: connfrontend/temp
  #   container_name: connfrontend
  #   restart: always
  #   depends_on:
  #     - connbackend
  #   ports:
  #       - "8080:80"
