version: "3.7"
services:
  connbackend:
    build:
      context: .
      dockerfile: Dockerfile_nodejs
      args:
        - DEFAULT_URL
        - DB_URL
    image: connbackend/temp
    container_name: connbackend
    restart: on-failure
    depends_on:
      - mongodb
    command: bash -c "node deploy_scripts/nodejs_init/wait_for_mongo.js && node index.js"
    volumes:
      - $PWD/static:/app/static
      - $PWD/deploy_scripts/nodejs_init:/app/nodejs_init
    ports:
        - "4000:4000"
    env_file: .env
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /var/log
    env_file: .env
    volumes:
      - $PWD/data/db:/data/db
      - $PWD/deploy_scripts/mongo_init:/docker-entrypoint-initdb.d
    ports:
        - 27017:27017
  connfrontend:
    build:
      context: ./vue-client
      dockerfile: Dockerfile_vue
    image: connfrontend/temp
    container_name: connfrontend
    restart: on-failure
    depends_on:
      - connbackend
    ports:
        - "8080:80"