export const LOGIN = 'LOGIN';
export const LOGIN_WITH_GOOGLE = 'LOGIN_WITH_GOOGLE';
export const LOGIN_WITH_OUTLOOK = 'LOGIN_WITH_OUTLOOK';
export const GET_INFO_ABOUT_USER = 'GET_INFO_ABOUT_USER';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const CREATE_EVENT = 'CREATE_EVENT';
export const GET_EVENTS = 'GET_EVENTS';
export const DELETE_EVENT = 'DELETE_EVENT';

export const GET_USERS = 'GET_USERS';

export const GET_USER = 'GET_USER';

export const LOGOUT = 'LOGOUT';
export const INSERT_USER_INFO = 'INSERT_USER_INFO';
export const CHECK_USER_INFO = 'CHECK_USER_INFO';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
