export const SET_POSTS = 'SET_POSTS';
export const ADD_POST = 'ADD_POST';

export const ADD_COMMENT_FOR_POST = 'ADD_COMMENT_FOR_POST';
export const ADD_LIKE_FOR_POST = 'ADD_LIKE_FOR_POST';
export const ADD_LIKE_FOR_COMMENT = 'ADD_LIKE_FOR_COMMENT';
export const ADD_ANSWER_FOR_COMMENT = 'ADD_ANSWER_FOR_COMMENT';
export const REMOVE_POST = 'REMOVE_POST';