export const SET_POSTS = 'SET_POSTS';
export const ADD_POST = 'ADD_POST';

export const ADD_COMMENT_FOR_POST = 'ADD_COMMENT_FOR_POST';
export const ADD_LIKE_FOR_POST = 'ADD_LIKE_FOR_POST';
export const ADD_LIKE_FOR_COMMENT = 'ADD_LIKE_FOR_COMMENT';
export const ADD_ANSWER_FOR_COMMENT = 'ADD_ANSWER_FOR_COMMENT';
export const REMOVE_POST = 'REMOVE_POST';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';

export const CHANGE_POST = 'CHANGE_POST';
export const CHANGE_COMMENT = 'CHANGE_COMMENT';


export const SET_POST_FOR_EDITING = 'SET_POST_FOR_EDITING';
export const SET_COMMENT_FOR_EDITING = 'SET_COMMENT_FOR_EDITING';
export const SET_EDIT_POST_VISIBLE = 'SET_EDIT_POST_VISIBLE';
export const SET_EDIT_COMMENT_VISIBLE = 'SET_EDIT_COMMENT_VISIBLE';
