name: PULL-REQUEST MASTER

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: BUILD FRONTEND
      run: docker-compose build --force-rm --no-cache connfrontend
    - name: BUILD BACKEND
      if: ${{ success() }}
      run: docker-compose build --force-rm --no-cache connbackend
